export const routes ={
    home:'/',
    login:'/login',
    registerPublication:'/registerPublication',
    registerVeterinary:'/registerVeterinary',
    publications:'/publications',
    alimentacion:'/alimentacion',
    enfermedades:'/enfermedades',
    vacunas:'/vacunas',
    route404: '/404',
    checkPub: '/checkPublications',
    publication:'/publications/:id/publication',
    veterinaryInfo:'/veterinary/:id/info',
    accountVeterinary:'/accountVeterinary/:id',
};